/*
  Author:   Pieter Van den Abeele
  E-mail:   pvdabeel@mac.com
  Copyright (c) 2005-2026, Pieter Van den Abeele

  Distributed under the terms of the LICENSE file in the root directory of this
  project.
*/


/** <module> SNAPSHOT
Snapshot and rollback mechanism for portage-ng. Records VDB state, world
set, and quickpkg'd binaries of replaced packages before merge operations,
enabling rollback to a previous system state.
*/

:- module(snapshot, []).

% =============================================================================
%  SNAPSHOT declarations
% =============================================================================

:- dynamic snapshot:active_id/1.


% -----------------------------------------------------------------------------
%  Snapshot directory helpers
% -----------------------------------------------------------------------------

%! snapshot:base_dir(-Dir) is det.
%
% Returns the base snapshot directory for the current host.

snapshot:base_dir(Dir) :-
  config:snapshot_dir(Dir).


%! snapshot:snapshot_dir(+Id, -Dir) is det.
%
% Returns the directory for a specific snapshot. Validates Id against
% path traversal (no slashes, no '..').

snapshot:snapshot_dir(Id, Dir) :-
  ( sanitize:safe_snapshot_id(Id) -> true
  ; throw(error(permission_error(access, snapshot, Id),
                context(snapshot:snapshot_dir/2, 'Invalid snapshot ID (path traversal rejected)')))
  ),
  snapshot:base_dir(Base),
  os:compose_path(Base, Id, Dir).


%! snapshot:binpkg_dir(+Id, -Dir) is det.
%
% Returns the binpkg subdirectory for a specific snapshot.

snapshot:binpkg_dir(Id, Dir) :-
  snapshot:snapshot_dir(Id, SnapDir),
  os:compose_path(SnapDir, binpkgs, Dir).


%! snapshot:manifest_path(+Id, -Path) is det.

snapshot:manifest_path(Id, Path) :-
  snapshot:snapshot_dir(Id, Dir),
  os:compose_path(Dir, 'manifest.pl', Path).


%! snapshot:world_path(+Id, -Path) is det.

snapshot:world_path(Id, Path) :-
  snapshot:snapshot_dir(Id, Dir),
  os:compose_path(Dir, 'world', Path).


%! snapshot:actions_path(+Id, -Path) is det.

snapshot:actions_path(Id, Path) :-
  snapshot:snapshot_dir(Id, Dir),
  os:compose_path(Dir, 'actions.pl', Path).


% -----------------------------------------------------------------------------
%  Snapshot ID generation
% -----------------------------------------------------------------------------

%! snapshot:generate_id(-Id) is det.
%
% Generates a snapshot ID from the current timestamp (YYYYMMDD-HHMMSS).

snapshot:generate_id(Id) :-
  get_time(Now),
  stamp_date_time(Now, DateTime, local),
  DateTime = date(Y, Mo, D, H, Mi, S, _, _, _),
  Si is truncate(S),
  snapshot:pad2(Mo, MoS), snapshot:pad2(D, DS),
  snapshot:pad2(H, HS), snapshot:pad2(Mi, MiS), snapshot:pad2(Si, SiS),
  atomic_list_concat([Y, MoS, DS, '-', HS, MiS, SiS], Id).


%! snapshot:pad2(+N, -Padded) is det.
%
% Zero-pads an integer to 2 digits.

snapshot:pad2(N, S) :-
  ( N < 10 -> format(atom(S), '0~d', [N]) ; format(atom(S), '~d', [N]) ).


% -----------------------------------------------------------------------------
%  Snapshot creation
% -----------------------------------------------------------------------------

%! snapshot:create(+Id, +Plan) is det.
%
% Creates a snapshot with the given ID. Records:
% 1. VDB manifest (all currently installed packages)
% 2. World set (copy of world file)
% 3. Planned actions (for rollback reference)

snapshot:create(Id, Plan) :-
  snapshot:snapshot_dir(Id, Dir),
  ( exists_directory(Dir)
  -> message:warning(['Snapshot already exists: ', Id]),
     fail
  ;  true
  ),
  make_directory_path(Dir),
  snapshot:write_manifest(Id),
  snapshot:copy_world(Id),
  snapshot:write_actions(Id, Plan),
  snapshot:binpkg_dir(Id, BinDir),
  make_directory_path(BinDir),
  assertz(snapshot:active_id(Id)),
  message:inform(['Snapshot created: ', Id]).


%! snapshot:write_manifest(+Id) is det.
%
% Dumps the current VDB state as Prolog facts into manifest.pl.

snapshot:write_manifest(Id) :-
  snapshot:manifest_path(Id, Path),
  get_time(Now),
  setup_call_cleanup(
    open(Path, write, S),
    ( format(S, '% Snapshot manifest~n', []),
      format(S, '% Generated by portage-ng~n~n', []),
      format(S, 'snapshot_timestamp(~w).~n~n', [Now]),
      forall(
        ( cache:ordered_entry(pkg, Entry, C, N, Ver),
          ( query:search(slot(Slot), pkg://Entry) -> true ; Slot = '0' )
        ),
        format(S, 'installed(~q, ~q, ~q, ~q).~n', [C, N, Ver, Slot])
      )
    ),
    close(S)
  ).


%! snapshot:copy_world(+Id) is det.
%
% Copies the current world set file into the snapshot directory.

snapshot:copy_world(Id) :-
  snapshot:world_path(Id, DestPath),
  config:world_file(SrcPath),
  ( exists_file(SrcPath)
  -> copy_file(SrcPath, DestPath)
  ;  true
  ).


%! snapshot:write_actions(+Id, +Plan) is det.
%
% Records the planned actions for reference during rollback.

snapshot:write_actions(Id, Plan) :-
  snapshot:actions_path(Id, Path),
  setup_call_cleanup(
    open(Path, write, S),
    ( format(S, '% Planned actions for snapshot ~w~n~n', [Id]),
      forall(
        ( member(Step, Plan),
          ( Step = [_|_] -> member(Rule, Step) ; Rule = Step ),
          snapshot:rule_action(Rule, C, N, Ver, Action, OldVer)
        ),
        format(S, 'action(~q, ~q, ~q, ~q, ~q).~n', [C, N, Ver, Action, OldVer])
      )
    ),
    close(S)
  ).


%! snapshot:rule_action(+Rule, -C, -N, -Ver, -Action, -OldVer) is semidet.
%
% Extracts action info from a plan rule for recording.

snapshot:rule_action(rule(Repo://Entry:Action?{Ctx}, _Body), C, N, Ver, Action, OldVer) :-
  cache:ordered_entry(Repo, Entry, C, N, Ver),
  ( memberchk(replaces(OldRepo://OldEntry), Ctx),
    cache:ordered_entry(OldRepo, OldEntry, _, _, OldVer0)
  -> OldVer = OldVer0
  ;  OldVer = none
  ).

snapshot:rule_action(assumed(rule(Repo://Entry:Action?{Ctx}, _Body)), C, N, Ver, Action, OldVer) :-
  cache:ordered_entry(Repo, Entry, C, N, Ver),
  ( memberchk(replaces(OldRepo://OldEntry), Ctx),
    cache:ordered_entry(OldRepo, OldEntry, _, _, OldVer0)
  -> OldVer = OldVer0
  ;  OldVer = none
  ).


% -----------------------------------------------------------------------------
%  Quickpkg of replaced packages
% -----------------------------------------------------------------------------

%! snapshot:quickpkg_old(+OldRepo, +OldEntry) is det.
%
% Creates a binary package of the currently installed version before
% it gets replaced. Uses the active snapshot ID. Called from the
% builder before the merge phase.

snapshot:quickpkg_old(OldRepo, OldEntry) :-
  ( snapshot:active_id(Id)
  -> snapshot:quickpkg_old(Id, OldRepo, OldEntry)
  ;  true
  ).


%! snapshot:quickpkg_old(+Id, +OldRepo, +OldEntry) is det.
%
% Runs `ebuild <old.ebuild> package` with PKGDIR set to the
% snapshot's binpkg directory.

snapshot:quickpkg_old(Id, OldRepo, OldEntry) :-
  ( ebuild_exec:ebuild_path(OldRepo, OldEntry, EbuildPath)
  -> snapshot:binpkg_dir(Id, BinDir),
     config:ebuild_command(EbuildCmd),
     ebuild_exec:collect_use_string(OldRepo, OldEntry, [], UseString),
     catch(
       ( process_create(
           path(EbuildCmd),
           ['--skip-manifest', EbuildPath, package],
           [stdout(null), stderr(null), process(Pid),
            environment(['USE'=UseString, 'PKGDIR'=BinDir])]),
         process_wait(Pid, exit(ExitCode)),
         ( ExitCode =:= 0
         -> true
         ;  cache:ordered_entry(OldRepo, OldEntry, C, N, _),
            message:warning(['quickpkg failed for ', C, '/', N, ' (exit ', ExitCode, ')'])
         )
       ),
       Error,
       ( cache:ordered_entry(OldRepo, OldEntry, C2, N2, _),
         message:warning(['quickpkg error for ', C2, '/', N2, ': ', Error])
       )
     )
  ;  true
  ).


% -----------------------------------------------------------------------------
%  Snapshot listing
% -----------------------------------------------------------------------------

%! snapshot:list is det.
%
% Lists all available snapshots for the current hostname.

snapshot:list :-
  snapshot:base_dir(Dir),
  ( exists_directory(Dir)
  -> directory_files(Dir, AllFiles),
     include(snapshot:is_snapshot_dir(Dir), AllFiles, SnapDirs),
     sort(SnapDirs, Sorted),
     ( Sorted == []
     -> message:inform('No snapshots found.')
     ;  nl,
        message:color(green),
        format('Available snapshots:~n'),
        message:color(normal),
        nl,
        forall(member(SnapId, Sorted),
          snapshot:print_snapshot_info(SnapId)
        ),
        nl
     )
  ;  message:inform('No snapshots found.')
  ).


%! snapshot:is_snapshot_dir(+Base, +Name) is semidet.

snapshot:is_snapshot_dir(Base, Name) :-
  Name \== '.',
  Name \== '..',
  os:compose_path(Base, Name, Full),
  exists_directory(Full),
  os:compose_path(Full, 'manifest.pl', ManifestPath),
  exists_file(ManifestPath).


%! snapshot:print_snapshot_info(+Id) is det.

snapshot:print_snapshot_info(Id) :-
  snapshot:manifest_path(Id, ManifestPath),
  ( snapshot:read_manifest_timestamp(ManifestPath, Timestamp)
  -> stamp_date_time(Timestamp, DateTime, local),
     format_time(atom(TimeStr), '%Y-%m-%d %H:%M:%S', DateTime)
  ;  TimeStr = 'unknown'
  ),
  snapshot:count_manifest_packages(ManifestPath, PkgCount),
  snapshot:count_binpkgs(Id, BinCount),
  format('  ~w~t~30|~w~t~52|~w pkgs~t~64|~w binpkgs~n', [Id, TimeStr, PkgCount, BinCount]).


%! snapshot:read_manifest_timestamp(+Path, -Timestamp) is semidet.

snapshot:read_manifest_timestamp(Path, Timestamp) :-
  setup_call_cleanup(
    open(Path, read, S),
    ( read_term(S, Term, []),
      snapshot:find_timestamp([Term], S, Timestamp)
    ),
    close(S)
  ).

snapshot:find_timestamp([], S, Timestamp) :-
  read_term(S, Term, []),
  Term \== end_of_file,
  snapshot:find_timestamp([Term], S, Timestamp).
snapshot:find_timestamp([snapshot_timestamp(T)|_], _, T) :- !.
snapshot:find_timestamp([_], S, Timestamp) :-
  snapshot:find_timestamp([], S, Timestamp).


%! snapshot:count_manifest_packages(+Path, -Count) is det.

snapshot:count_manifest_packages(Path, Count) :-
  catch(
    setup_call_cleanup(
      open(Path, read, S),
      ( snapshot:count_installed_terms(S, 0, Count) ),
      close(S)
    ),
    _,
    Count = 0
  ).

snapshot:count_installed_terms(S, Acc, Count) :-
  read_term(S, Term, []),
  ( Term == end_of_file
  -> Count = Acc
  ;  ( Term = installed(_, _, _, _) -> Acc1 is Acc + 1 ; Acc1 = Acc ),
     snapshot:count_installed_terms(S, Acc1, Count)
  ).


%! snapshot:count_binpkgs(+Id, -Count) is det.

snapshot:count_binpkgs(Id, Count) :-
  snapshot:binpkg_dir(Id, BinDir),
  ( exists_directory(BinDir)
  -> catch(
       ( directory_files(BinDir, CatDirs),
         aggregate_all(count,
           ( member(Cat, CatDirs),
             Cat \== '.', Cat \== '..',
             os:compose_path(BinDir, Cat, CatPath),
             exists_directory(CatPath),
             directory_files(CatPath, Files),
             member(F, Files),
             F \== '.', F \== '..',
             ( sub_atom(F, _, _, 0, '.tbz2')
             ; sub_atom(F, _, _, 0, '.gpkg.tar')
             )
           ),
           Count)
       ),
       _,
       Count = 0
     )
  ;  Count = 0
  ).


% -----------------------------------------------------------------------------
%  Snapshot diff (pretend rollback)
% -----------------------------------------------------------------------------

%! snapshot:diff(+Id) is det.
%
% Compares a snapshot's manifest against the current VDB state and
% prints what changed since the snapshot was taken.

snapshot:diff(Id) :-
  snapshot:manifest_path(Id, ManifestPath),
  ( \+ exists_file(ManifestPath)
  -> message:failure(['Snapshot not found: ', Id]),
     fail
  ;  true
  ),
  snapshot:load_manifest_packages(ManifestPath, SnapPkgs),
  snapshot:current_vdb_packages(CurrentPkgs),
  snapshot:compute_diff(SnapPkgs, CurrentPkgs, Added, Removed, Changed),
  length(Added, NA), length(Removed, NR), length(Changed, NC),
  nl,
  message:color(cyan),
  format('Diff against snapshot "~w":~n', [Id]),
  message:color(normal),
  ( NA =:= 0, NR =:= 0, NC =:= 0
  -> format('  (no changes since snapshot)~n')
  ;  ( NA > 0
     -> message:color(green),
        format('~n  Installed since snapshot (~w):~n', [NA]),
        forall(member(pkg(C, N, V, _), Added),
          ( snapshot:version_str(V, VS),
            format('    + ~w/~w-~w~n', [C, N, VS]) )),
        message:color(normal)
     ;  true
     ),
     ( NR > 0
     -> message:color(red),
        format('~n  Removed since snapshot (~w):~n', [NR]),
        forall(member(pkg(C, N, V, _), Removed),
          ( snapshot:version_str(V, VS),
            format('    - ~w/~w-~w~n', [C, N, VS]) )),
        message:color(normal)
     ;  true
     ),
     ( NC > 0
     -> message:color(orange),
        format('~n  Version changed since snapshot (~w):~n', [NC]),
        forall(member(changed(C, N, _Slot, OldV, NewV), Changed),
          ( snapshot:version_str(OldV, OVS),
            snapshot:version_str(NewV, NVS),
            format('    ~~ ~w/~w  ~w -> ~w~n', [C, N, OVS, NVS]) )),
        message:color(normal)
     ;  true
     ),
     snapshot:count_binpkgs(Id, BinCount),
     format('~n  Summary: +~w -~w ~~~w (~w binpkgs available for rollback)~n', [NA, NR, NC, BinCount])
  ),
  nl.


%! snapshot:version_str(+Ver, -Str) is det.

snapshot:version_str(version(_,_,_,_,_,_,Full), Full) :- !.
snapshot:version_str(version_none, '') :- !.
snapshot:version_str(V, S) :- format(atom(S), '~w', [V]).


%! snapshot:load_manifest_packages(+Path, -Pkgs) is det.

snapshot:load_manifest_packages(Path, Pkgs) :-
  setup_call_cleanup(
    open(Path, read, S),
    snapshot:read_all_installed(S, Pkgs),
    close(S)
  ).

snapshot:read_all_installed(S, Pkgs) :-
  read_term(S, Term, []),
  ( Term == end_of_file
  -> Pkgs = []
  ;  ( Term = installed(C, N, V, Slot)
     -> Pkgs = [pkg(C, N, V, Slot)|Rest]
     ;  Pkgs = Rest
     ),
     snapshot:read_all_installed(S, Rest)
  ).


%! snapshot:current_vdb_packages(-Pkgs) is det.

snapshot:current_vdb_packages(Pkgs) :-
  findall(pkg(C, N, Ver, Slot),
    ( cache:ordered_entry(pkg, Entry, C, N, Ver),
      ( query:search(slot(Slot), pkg://Entry) -> true ; Slot = '0' )
    ),
    Pkgs0),
  sort(Pkgs0, Pkgs).


%! snapshot:compute_diff(+SnapPkgs, +CurrentPkgs, -Added, -Removed, -Changed) is det.

snapshot:compute_diff(SnapPkgs, CurrentPkgs, Added, Removed, Changed) :-
  findall(pkg(C, N, V, S),
    ( member(pkg(C, N, V, S), CurrentPkgs),
      \+ member(pkg(C, N, _, S), SnapPkgs)
    ),
    Added),
  findall(pkg(C, N, V, S),
    ( member(pkg(C, N, V, S), SnapPkgs),
      \+ member(pkg(C, N, _, S), CurrentPkgs)
    ),
    Removed),
  findall(changed(C, N, S, OldV, NewV),
    ( member(pkg(C, N, OldV, S), SnapPkgs),
      member(pkg(C, N, NewV, S), CurrentPkgs),
      OldV \== NewV
    ),
    Changed).


% -----------------------------------------------------------------------------
%  Rollback execution
% -----------------------------------------------------------------------------

%! snapshot:rollback(+Id) is det.
%
% Rolls back to a snapshot: reinstalls saved binpkgs and restores
% the world set.

snapshot:rollback(Id) :-
  snapshot:snapshot_dir(Id, Dir),
  ( \+ exists_directory(Dir)
  -> message:failure(['Snapshot not found: ', Id]),
     fail
  ;  true
  ),
  snapshot:rollback_binpkgs(Id),
  snapshot:rollback_world(Id),
  message:success(['Rollback to snapshot "', Id, '" complete.']).


%! snapshot:rollback_binpkgs(+Id) is det.
%
% Reinstalls all saved binpkgs from the snapshot using
% `ebuild <binpkg.ebuild> merge`.

snapshot:rollback_binpkgs(Id) :-
  snapshot:binpkg_dir(Id, BinDir),
  ( exists_directory(BinDir)
  -> snapshot:find_binpkgs(BinDir, BinPkgs),
     length(BinPkgs, N),
     ( N > 0
     -> format('Reinstalling ~w packages from snapshot...~n', [N]),
        forall(member(binpkg(C, N0, BinPath), BinPkgs),
          snapshot:reinstall_binpkg(C, N0, BinPath)
        )
     ;  message:inform('No binpkgs to reinstall.')
     )
  ;  message:inform('No binpkgs directory in snapshot.')
  ).


%! snapshot:find_binpkgs(+BinDir, -BinPkgs) is det.

snapshot:find_binpkgs(BinDir, BinPkgs) :-
  directory_files(BinDir, CatDirs),
  findall(binpkg(Cat, Name, FullPath),
    ( member(Cat, CatDirs),
      Cat \== '.', Cat \== '..',
      os:compose_path(BinDir, Cat, CatPath),
      exists_directory(CatPath),
      directory_files(CatPath, Files),
      member(F, Files),
      F \== '.', F \== '..',
      ( sub_atom(F, _, _, 0, '.tbz2')
      ; sub_atom(F, _, _, 0, '.gpkg.tar')
      ),
      os:compose_path(CatPath, F, FullPath),
      ( sub_atom(F, 0, _, _, Name0)
      -> Name = Name0
      ;  Name = F
      )
    ),
    BinPkgs).


%! snapshot:reinstall_binpkg(+Category, +Name, +BinPath) is det.
%
% Reinstalls a single binpkg. Uses emerge --usepkg or direct
% ebuild invocation depending on what's available.

snapshot:reinstall_binpkg(Category, _Name, BinPath) :-
  config:ebuild_command(EbuildCmd),
  format('  Reinstalling ~w from ~w...~n', [Category, BinPath]),
  catch(
    ( process_create(
        path(EbuildCmd),
        ['--skip-manifest', BinPath, merge],
        [stdout(null), stderr(null), process(Pid)]),
      process_wait(Pid, exit(ExitCode)),
      ( ExitCode =:= 0
      -> format('  Done.~n')
      ;  message:warning(['Reinstall failed for ', Category, ' (exit ', ExitCode, ')'])
      )
    ),
    Error,
    message:warning(['Reinstall error for ', Category, ': ', Error])
  ).


%! snapshot:rollback_world(+Id) is det.
%
% Restores the world set from the snapshot.

snapshot:rollback_world(Id) :-
  snapshot:world_path(Id, SnapWorld),
  ( exists_file(SnapWorld)
  -> config:world_file(CurrentWorld),
     copy_file(SnapWorld, CurrentWorld),
     world:load,
     message:inform('World set restored from snapshot.')
  ;  message:inform('No world file in snapshot, skipping world restore.')
  ).


% -----------------------------------------------------------------------------
%  Snapshot deletion
% -----------------------------------------------------------------------------

%! snapshot:delete(+Id) is det.
%
% Deletes a snapshot directory and all its contents.

snapshot:delete(Id) :-
  snapshot:snapshot_dir(Id, Dir),
  ( exists_directory(Dir)
  -> catch(
       ( delete_directory_and_contents(Dir),
         message:inform(['Snapshot deleted: ', Id])
       ),
       Error,
       message:warning(['Failed to delete snapshot ', Id, ': ', Error])
     )
  ;  message:warning(['Snapshot not found: ', Id])
  ).


% -----------------------------------------------------------------------------
%  Cleanup on build completion
% -----------------------------------------------------------------------------

%! snapshot:finalize is det.
%
% Clears the active snapshot ID after build completes.

snapshot:finalize :-
  retractall(snapshot:active_id(_)).