#!/bin/bash

executable=cmake

path_to_executable=$(which $executable)

if ! [ -x "$path_to_executable" ]; then
  echo "$executable is not installed in your PATH"
  exit 1
fi

LOCAL=${1}

cd ${LOCAL}

mkdir -p build
cd build
CFLAGS="-O3 -march=native -pipe" CXXFLAGS="-O3 -march=native -pipe" cmake -G 'Unix Makefiles' -DSWIPL_PACKAGES_JAVA=OFF -DSWIPL_PACKAGES_X=OFF -DINSTALL_DOCUMENTATION=OFF ..
CFLAGS="-O3 -march=native -pipe" CXXFLAGS="-O3 -march=native -pipe" make 
#sudo make install

