#!/bin/bash

# Calls graphviz to turn exported .dot files into interactive .svg 

# Make sure you have at least Graphviz v11.

# ${1} = remote
# ${2} = local

PV_FMT_DOT=$'\033[1;90m% [%{progress-amount-only}] - Creating SVG graphs  [ %{bar-shaded} | %t | %e ]\033[0m'


if [ -f "${1}/.lastgraph" ]; then

  find "${1}" -type f -iname "*.dot" -mnewer "${1}/.lastgraph" \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" -mnewer "${1}/.lastgraph" | wc -l) --eta --timer --progress -F "$PV_FMT_DOT" \
  | sed 's/\.dot$//' \
  | xargs -P"56" -n1 -I{} \
  dot -Tsvg {}.dot -o {}.svg

else 

  find "${1}" -type f -iname "*.dot" \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" | wc -l) --eta --timer --progress -F "$PV_FMT_DOT" \
  | sed 's/\.dot$//' \
  | xargs -P"56" -n1 -I{} \
  dot -Tsvg {}.dot -o {}.svg


fi
touch "${1}/.lastgraph"
