#!/bin/bash

# Calls graphviz to turn exported .dot files into interactive .svg 

# Make sure you have at least Graphviz v11.

# ${1} = remote
# ${2} = local

PV_FMT_DOT=$'\033[1;90m% [%{progress-amount-only}] - Creating SVG graphs  [ %{bar-shaded} | %t | %e ]\033[0m'


if [ -f "${1}/.lastgraph" ]; then

  find "${1}" -type f -iname "*.dot" -mnewer "${1}/.lastgraph" -print0 \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" -mnewer "${1}/.lastgraph" | wc -l) --eta --timer --progress -F "$PV_FMT_DOT" -0 \
  | xargs -0 -P"56" -n1 -I{} \
  sh -c 'f="{}"; dot -Tsvg "$f" -o "${f%.dot}.svg"'

else 

  find "${1}" -type f -iname "*.dot" -print0 \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" | wc -l) --eta --timer --progress -F "$PV_FMT_DOT" -0 \
  | xargs -0 -P"56" -n1 -I{} \
  sh -c 'f="{}"; dot -Tsvg "$f" -o "${f%.dot}.svg"'

fi
touch "${1}/.lastgraph"
