# Copyright 2026 Pieter Van den Abeele
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit git-r3

DESCRIPTION="Declarative reasoning engine for Gentoo package configuration"
HOMEPAGE="https://github.com/pvdabeel/portage-ng
	http://www.portage-ng.org/"
EGIT_REPO_URI="https://github.com/pvdabeel/portage-ng.git"

LICENSE="BSD-2"
SLOT="0"
KEYWORDS=""
IUSE="graph"

PROPERTIES="live"

# SWI-Prolog provides the runtime. Components required by portage-ng
# (see Documentation/Handbook/02-doc-installation.md): ssl, pcre, gmp.
# Line editing is optional: SWI USE=cli (libedit) or USE=readline
# (GNU readline) enables --shell history. Neither is required for
# --pretend / --merge.
RDEPEND="
	>=dev-lang/swi-prolog-10.0.0[gmp,pcre,ssl]
	>=app-shells/bash-5
	dev-libs/openssl
	dev-vcs/git
	net-misc/curl
	sys-apps/coreutils
	graph? ( media-gfx/graphviz )
"
DEPEND="${RDEPEND}"
# Traditional Portage supplies the ebuild(1) builder used by --merge.
PDEPEND="sys-apps/portage"

src_compile() {
	# Packaged installs use the FILESDIR wrapper (swipl + -p portage=...),
	# so there is no stand-alone binary to bake. Smoke-check that the
	# sources load under the same SWI-Prolog that will run at runtime.
	swipl -q \
		-f portage-ng.pl \
		-p "portage=${S}" \
		-g "halt(0)" \
		-t "halt(1)" || die "SWI-Prolog failed to load portage-ng.pl"
}

src_install() {
	local libdir="/usr/lib/${PN}"

	# Runtime application tree. Knowledge/*.qlf are generated by --sync
	# and intentionally not shipped from git.
	insinto "${libdir}"
	doins portage-ng.pl LICENSE README.md Makefile
	doins -r Source
	dodoc CONTRIBUTING.md

	insinto "${libdir}/Knowledge"
	doins Knowledge/README.md
	keepdir "${libdir}/Knowledge"

	# Host Private secrets must never ship; keep templates only.
	rm -f "${ED}${libdir}"/Source/Config/Private/api_key.pl || die
	rm -f "${ED}${libdir}"/Source/Config/Private/passwords.pl || die

	# Replace the developer default (Repository/portage-git under the
	# checkout) with Gentoo system paths for packaged installs.
	insinto "${libdir}/Source/Config"
	newins "${FILESDIR}"/system-default.pl default.pl

	fperms 755 "${libdir}/Source/Application/Wrapper/portage-ng-dev"
	fperms 755 "${libdir}/Source/Domain/Gentoo/Ebuild/ebuild-depend.sh"

	sed -e "s|@LIBDIR@|${EPREFIX}${libdir}|g" \
		"${FILESDIR}"/portage-ng.sh > "${T}"/portage-ng || die
	dobin "${T}"/portage-ng

	doman Documentation/Manpage/portage-ng.1
}

pkg_postinst() {
	elog "portage-ng is installed under ${EPREFIX}/usr/lib/${PN}."
	elog "Run \`portage-ng --mode standalone --sync\` once to build"
	elog "Knowledge/kb.qlf from your Portage tree, then use"
	elog "\`portage-ng --mode standalone --pretend <atom>\`."
	elog
	elog "Override repository paths with a host config at"
	elog "${EPREFIX}/usr/lib/${PN}/Source/Config/\$(hostname).pl"
	use graph || elog "USE=graph pulls in Graphviz for --graph output."
}
