#!/bin/bash
# tinderbox-ng.d/compare-matrix.sh
#
# Drive `tinderbox-ng compare` over a list of packages, parse each
# summary table, and emit a single-line TSV record per target plus a
# concise stdout report. Designed to be invoked from the host via
#
#   ssh root@vm-linux.local 'compare-matrix.sh --mode pretend pkg1 pkg2 ...'
#
# Output goes to /srv/tinderbox-ng/reports/compare-matrix-<stamp>/.
#
# Exit code: 0 if every comparison's portage-ng side matched (or
# improved on) emerge in completion + VDB count; 1 otherwise.

set -euo pipefail

MODE="--pretend"
LABEL_PREFIX=""
KEEP=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --pretend|-p) MODE="--pretend"; shift ;;
    --build|-b)   MODE="--build";   shift ;;
    --keep)       KEEP=1;            shift ;;
    --label-prefix) LABEL_PREFIX="$2"; shift 2 ;;
    --) shift; break ;;
    -*) echo "unknown flag $1" >&2; exit 2 ;;
    *)  break ;;
  esac
done

PACKAGES=("$@")
[[ ${#PACKAGES[@]} -gt 0 ]] || { echo "usage: compare-matrix.sh [--pretend|--build] [--keep] [--label-prefix P] pkg..." >&2; exit 2; }

STAMP="$(date +%Y%m%dT%H%M%S)"
OUTDIR="/srv/tinderbox-ng/reports/compare-matrix-$STAMP"
TSV="$OUTDIR/results.tsv"
mkdir -p "$OUTDIR"

# TSV header: easy to load into pandas/sqlite later if needed.
printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
  target mode pn_exit em_exit pn_actions em_actions pn_completed em_completed pn_vdb em_vdb vdb_delta \
  > "$TSV"

mismatches=0
for pkg in "${PACKAGES[@]}"; do
  label="${LABEL_PREFIX}$(printf '%s' "$pkg" | tr -c '[:alnum:]' '_' | sed 's/^_*//;s/_*$//')"
  log="$OUTDIR/${label}.log"

  printf '\n========== %s (%s) ==========\n' "$pkg" "$MODE"

  cmp_args=("$MODE" --label "$label")
  [[ $KEEP -eq 1 ]] && cmp_args+=(--keep)

  set +e
  /usr/local/sbin/tinderbox-ng compare "${cmp_args[@]}" "$pkg" >"$log" 2>&1
  rc=$?
  set -e

  # Parse the report table out of $log. The format is generated by
  # tinderbox-ng's _compare_summarize() and is stable.
  pn_exit="$(awk -F'│' '/^│ exit /{print $3}' "$log" | tr -d ' ' | head -n1)"
  em_exit="$(awk -F'│' '/^│ exit /{print $4}' "$log" | tr -d ' ' | head -n1)"
  pn_actions="$(awk -F'│' '/^│ plan actions /{print $3}' "$log" | tr -d ' ' | head -n1)"
  em_actions="$(awk -F'│' '/^│ plan actions /{print $4}' "$log" | tr -d ' ' | head -n1)"
  pn_completed="$(awk -F'│' '/^│ completed /{print $3}' "$log" | tr -d ' ' | head -n1)"
  em_completed="$(awk -F'│' '/^│ completed /{print $4}' "$log" | tr -d ' ' | head -n1)"
  pn_vdb="$(awk -F'│' '/^│ merged into VDB /{print $3}' "$log" | tr -d ' ' | head -n1)"
  em_vdb="$(awk -F'│' '/^│ merged into VDB /{print $4}' "$log" | tr -d ' ' | head -n1)"

  # Default to "?" for missing fields rather than empty (cleaner reports)
  for v in pn_exit em_exit pn_actions em_actions pn_completed em_completed pn_vdb em_vdb; do
    [[ -z "${!v}" ]] && eval "$v=?"
  done

  vdb_delta="="
  if [[ "$pn_vdb" =~ ^[0-9]+$ && "$em_vdb" =~ ^[0-9]+$ ]]; then
    if [[ "$pn_vdb" -lt "$em_vdb" ]]; then
      vdb_delta="-$((em_vdb - pn_vdb))"
      mismatches=$((mismatches + 1))
    elif [[ "$pn_vdb" -gt "$em_vdb" ]]; then
      vdb_delta="+$((pn_vdb - em_vdb))"
    fi
  fi

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$pkg" "$MODE" "$pn_exit" "$em_exit" "$pn_actions" "$em_actions" \
    "$pn_completed" "$em_completed" "$pn_vdb" "$em_vdb" "$vdb_delta" \
    >> "$TSV"

  printf '  -> tinderbox-ng compare rc=%d  exit pn=%s em=%s  vdb pn=%s em=%s (delta %s)\n' \
    "$rc" "$pn_exit" "$em_exit" "$pn_vdb" "$em_vdb" "$vdb_delta"
done

printf '\n========== summary ==========\n'
printf 'TSV: %s\n' "$TSV"
printf 'Per-package logs: %s/<label>.log\n\n' "$OUTDIR"

# Render an aligned summary table to stdout
column -t -s $'\t' "$TSV"

[[ $mismatches -eq 0 ]] && exit 0 || exit 1
