#!/bin/sh

# Make sure you have portage-ng installed!

#if ! [ -x "$(portage-ng -V)" ]; then
#  echo "Portage-ng is not installed in your PATH" 
#  exit 1
#fi

while true
do

cd '/Volumes/Disk 1/Repository/portage-git/';

git fetch --prune;
LOCAL=$(git rev-parse HEAD);
REMOTE=$(git rev-parse @{u});

# If our local revision id doesn't match the remote, we will need to pull the changes

if [ $LOCAL != $REMOTE ]; then
#if [ true ]; then
    
    echo ">>> Commit found, updating"
    echo "--- `date`" 
    echo
    portage-ng --clear # clear repository
    portage-ng --sync  # sync repository
    portage-ng --graph # update graph
    
    pushd '/Volumes/Disk 1/Graph/'

    git add .
    git commit -m "Update" 
    git push -u origin master 

    popd
    echo
    echo ">>> Done processing"
else 
    echo ">>> No commit found, sleeping" 
    echo "--- `date`" 
fi
sleep 60
done
