#!/bin/sh

NAME=${1}
LOCAL=${2}
METADATA=${3}

cd ${LOCAL}


# EAPI:
#   need to regenerate metadata cache from ebuilds here:
#   egencache
#   find . -type f | sed -e "s/.\//metadata(\'/" | sed -e "s/$/\')./"


# CMAKE:

mkdir -p ${METADATA}
mkdir -p ${METADATA}/github

for version in `git tag -l "V*"`; do 
  eapiversion=`echo ${version:1} | sed 's/-rc/_rc/g'`
  touch ${METADATA}/github/${NAME}-${eapiversion}; 
done

for version in `git tag -l "v*"`; do 
  eapiversion=`echo ${version:1} | sed 's/-rc/_rc/g'`
  touch ${METADATA}/github/${NAME}-${eapiversion}; 
done


touch ${METADATA}/github/${NAME}-9999 # master branch
