#!/bin/bash

# Calls graphviz to turn exported .dot files into interactive .svg 

# Make sure you have at least Graphviz v11.

# ${1} = remote
# ${2} = local
if [ -f "${1}/.lastgraph" ]; then

  find "${1}" -type f -iname "*.dot" -mnewer "${1}/.lastgraph" \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" | wc -l) --eta --timer --progress  \
  | sed 's/\.dot$//' \
  | xargs -P"65" -n1 -I{} \
  dot -Tsvg {}.dot -o {}.svg

else 

  find "${1}" -type f -iname "*.dot" \
  | pv -l -s $(find "${1}" -type f -iname "*.dot" | wc -l) --eta --timer --progress  \
  | sed 's/\.dot$//' \
  | xargs -P"65" -n1 -I{} \
  dot -Tsvg {}.dot -o {}.svg


fi
touch "${1}/.lastgraph"
